### ISSUE TITLE
Index out of range when results for key are not available in search

### ISSUE THREAD

**Issue by hagaram** [alisww/py-manga#2]
Hi, 
I'm just getting started with python, so I didn't want to create a pull request, etc. as I think I'm not skilled enough, but I've run into an issue.

When you search for a keyword, in my case it was 'bleach', you get something like this:

```
pymanga.search('bleach')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/...py-manga/pymanga/api.py", line 13, in search
    'authors': search_parsers.parse_authors(lists[3])
```

It happens, because there are no authors with this name in the result. The same thing happens, when the is no result for releases etc. I think there should be some kind of default value e.g. empty string, or some try/except mechanism.

Regards,
Michal

**Comment by kore-signet** [comment]
Hi!! Thanks for reporting it.
Working to fix right now c:

**Comment by kore-signet** [comment]
Fixed in https://github.com/alisww/py-manga/commit/4b6e84691c5dad19f84cd3aa52dd3aeb5df2eec6

Thanks a lot! And by the way, feel free to make pull requests - it's a great way to learn :)
