### ISSUE TITLE
Error when series has no image

### ISSUE THREAD

**Issue by mizaki** [alisww/py-manga#6]
Hi,

It appears when there's no image found series_parsers.py throws the error: 

line 304, in _parse_col_2
    manga["image"] = contents[0].center.img["src"]
AttributeError: 'NoneType' object has no attribute 'img'

I changed it to a try:

    try:
        manga["image"] = contents[0].center.img["src"]
    except:
        manga["image"] = None

**Comment by kore-signet** [comment]
fixed in 66af5b97f1b08bf098e2cd2eaebe5c0ef40b3317
